from pathlib import Path

path = Path('build/pricingSellerRateRequestResponsibilities.ts')
text = path.read_text()
old = '''  const supportCard = `          <div class="crystal-soft space-y-4 p-4 md:p-5">\\n            <div>\\n              <p class="font-black">Documentos de respaldo de la solicitud</p>`
  const sellerHandlingCard = `          <div v-if="sellerRequestMode && shipmentModeForApi === 'Fcl'" class="crystal-soft space-y-3 p-4 md:p-5">\\n            <div>\\n              <p class="font-black">Muellaje en destino</p>\\n              <p class="mt-1 text-xs font-semibold text-[var(--dh-text-muted)]">Ventas puede indicar si el movimiento será Anticipado o Redestino. La selección viaja a Pricing con la solicitud.</p>\\n            </div>\\n            <div class="grid gap-3 sm:grid-cols-2">\\n              <button type="button" class="crystal-flag" :class="sellerPortHandlingMode === 'Anticipado' ? 'crystal-flag--active' : ''" @click="sellerPortHandlingMode = sellerPortHandlingMode === 'Anticipado' ? '' : 'Anticipado'">\\n                <Check v-if="sellerPortHandlingMode === 'Anticipado'" class="h-4 w-4" /> Anticipado\\n              </button>\\n              <button type="button" class="crystal-flag" :class="sellerPortHandlingMode === 'Redestino' ? 'crystal-flag--active' : ''" @click="sellerPortHandlingMode = sellerPortHandlingMode === 'Redestino' ? '' : 'Redestino'">\\n                <Check v-if="sellerPortHandlingMode === 'Redestino'" class="h-4 w-4" /> Redestino\\n              </button>\\n            </div>\\n          </div>\\n\\n${supportCard}`
  code = replaceOne(code, supportCard, sellerHandlingCard, 'seller port handling card')
'''
new = '''  const supportHeading = `            <div>\\n              <p class="font-black">Documentos de respaldo de la solicitud</p>\\n              <p class="mt-1 text-xs font-semibold text-[var(--dh-text-muted)]">Imágenes, PDF, Word y Excel quedan guardados en Storage y vinculados a esta solicitud.</p>\\n            </div>`
  const sellerHandlingCard = `            <div v-if="sellerRequestMode && shipmentModeForApi === 'Fcl'" class="mb-4 space-y-3 rounded-2xl border border-[rgb(var(--dh-primary-rgb)/0.28)] bg-[var(--dh-card)] p-4">\\n              <div>\\n                <p class="font-black">Muellaje en destino</p>\\n                <p class="mt-1 text-xs font-semibold text-[var(--dh-text-muted)]">Ventas puede indicar si el movimiento será Anticipado o Redestino. La selección viaja a Pricing con la solicitud.</p>\\n              </div>\\n              <div class="grid gap-3 sm:grid-cols-2">\\n                <button type="button" class="crystal-flag" :class="sellerPortHandlingMode === 'Anticipado' ? 'crystal-flag--active' : ''" @click="sellerPortHandlingMode = sellerPortHandlingMode === 'Anticipado' ? '' : 'Anticipado'">\\n                  <Check v-if="sellerPortHandlingMode === 'Anticipado'" class="h-4 w-4" /> Anticipado\\n                </button>\\n                <button type="button" class="crystal-flag" :class="sellerPortHandlingMode === 'Redestino' ? 'crystal-flag--active' : ''" @click="sellerPortHandlingMode = sellerPortHandlingMode === 'Redestino' ? '' : 'Redestino'">\\n                  <Check v-if="sellerPortHandlingMode === 'Redestino'" class="h-4 w-4" /> Redestino\\n                </button>\\n              </div>\\n            </div>\\n\\n${supportHeading}`
  code = replaceOne(code, supportHeading, sellerHandlingCard, 'seller port handling card')
'''
count = text.count(old)
if count != 1:
    raise SystemExit(f'Expected one old support anchor block, found {count}')
path.write_text(text.replace(old, new))
