import './assets/main.css'
import './assets/responsive.css'
import './assets/pricing-rate-navigation.css'
import './assets/pricing-metric-colors.css'

import { createApp, nextTick, watch } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'

import es from './core/i18n/es.json'
import en from './core/i18n/en.json'
import App from './App.vue'
import router from './core/router'
import { useLocale } from '@/core/stores/locale'
import { useThemeStore } from '@/core/stores/themeStore'
import { useBrandingStore } from '@/core/stores/brandingStore'
import { createUiTextBridge } from '@/core/i18n/uiTextBridge'
import { installAuditNavigation } from '@/core/audit/installAuditNavigation'

const STALE_CHUNK_RELOAD_KEY = 'dhole:stale-chunk-reload'
const STALE_CHUNK_RELOAD_WINDOW_MS = 30_000

function isStaleChunkError(error: unknown) {
  const message = error instanceof Error ? error.message : String(error ?? '')
  const normalized = message.toLowerCase()

  return normalized.includes('error loading dynamically imported module')
    || normalized.includes('failed to fetch dynamically imported module')
    || normalized.includes('importing a module script failed')
    || normalized.includes('unable to preload css')
}

function recoverFromStaleChunk(error: unknown) {
  if (!isStaleChunkError(error)) return false

  const now = Date.now()
  const lastReload = Number(sessionStorage.getItem(STALE_CHUNK_RELOAD_KEY) ?? '0')

  // A deployment replaces Vite fingerprinted chunks. An already-open tab can still
  // reference a chunk from the previous build, so reload once to obtain the current
  // index/module graph. The time guard prevents an infinite loop for genuine failures.
  if (!Number.isFinite(lastReload) || now - lastReload > STALE_CHUNK_RELOAD_WINDOW_MS) {
    sessionStorage.setItem(STALE_CHUNK_RELOAD_KEY, String(now))
    window.location.reload()
    return true
  }

  return false
}

// Vite emits this before a stale preload/dynamic import bubbles into Vue Router.
window.addEventListener('vite:preloadError', (event) => {
  event.preventDefault()
  recoverFromStaleChunk((event as Event & { payload?: unknown }).payload)
})

router.onError((error) => {
  recoverFromStaleChunk(error)
})

router.afterEach(() => {
  // Once a navigation succeeds with the current build, allow a future deployment to
  // trigger one fresh recovery again.
  sessionStorage.removeItem(STALE_CHUNK_RELOAD_KEY)
})

const PublicOriginOfficeView = () => import('@/modules/pricing/views/PublicOriginOfficeView.vue')

// Public commercial landing page. It deliberately lives outside MainLayout and does not
// expose authenticated Dhole navigation. The POL is carried in the query string so every
// QR can point to the same stable /origin route.
router.addRoute({
  path: '/origin',
  name: 'public-origin-office',
  component: PublicOriginOfficeView,
  meta: { public: true },
})

// Backwards-compatible public URLs generated by previous staging versions.
router.addRoute({
  path: '/origin/:polCode',
  name: 'public-origin-office-with-pol',
  redirect: (to) => ({
    name: 'public-origin-office',
    query: { ...to.query, pol: String(to.params.polCode ?? '') },
  }),
  meta: { public: true },
})

router.addRoute({
  path: '/origen/:polCode',
  name: 'public-origin-office-es-legacy',
  redirect: (to) => ({
    name: 'public-origin-office',
    query: { ...to.query, pol: String(to.params.polCode ?? '') },
  }),
  meta: { public: true },
})

router.addRoute({
  path: '/origin-office/:polCode',
  name: 'public-origin-office-legacy',
  redirect: (to) => ({
    name: 'public-origin-office',
    query: { ...to.query, pol: String(to.params.polCode ?? '') },
  }),
  meta: { public: true },
})

const app = createApp(App)
const pinia = createPinia()
app.use(pinia)
app.use(router)
installAuditNavigation(router)

const localeStore = useLocale()
const themeStore = useThemeStore()
const brandingStore = useBrandingStore()
themeStore.applyTheme()
brandingStore.applyCachedOrDefault()

const i18n = createI18n({ legacy: false, locale: localeStore.getLocale(), fallbackLocale: 'en', messages: { en, es } })
const uiTextBridge = createUiTextBridge(() => localeStore.getLocale())

watch(() => localeStore.getLocale(), async (newLocale) => {
  i18n.global.locale.value = newLocale
  document.documentElement.lang = newLocale
  await nextTick()
  uiTextBridge.refresh()
})

app.use(i18n)
document.documentElement.lang = localeStore.getLocale()
app.mount('#app')
uiTextBridge.start()
